#!/usr/bin/env python3
"""Deterministic original MINIX V2 image; no host mkfs dependency.

Reference: minix-2.0.0/src/fs/{super.h,type.h,const.h}. Block/zone size
1024, 32 inodes, 14-byte names. Physical final block is outside s_zones
and remains reserved for CP32's restored-sector device diagnostic.
"""
import argparse
from pathlib import Path
import struct

README = b'CP32 MINIX V2 RAM filesystem.\nRead-only filesystem bring-up.\n'

def build_image():
    disk = bytearray(65536)
    disk[1024:1048] = struct.pack('<6HIHHI', 32, 0, 1, 1, 6, 0,
                                  0x7fffffff, 0x2468, 0, 63)
    # Reserved bit zero, three inodes/zones in use, and all unavailable bits.
    for offset, usable in ((2048, 32), (3072, 57)):
        bitmap = bytearray(b'\xff' * 1024)
        for bit in range(4, usable + 1):
            bitmap[bit // 8] &= ~(1 << (bit % 8))
        disk[offset:offset+1024] = bitmap

    def inode(number, mode, links, size, zone):
        raw = struct.pack('<4H4I10I', mode, links, 0, 0, size, 0, 0, 0,
                          zone, *([0] * 9))
        offset = 4096 + (number-1)*64
        disk[offset:offset+64] = raw

    def directory(zone, entries):
        for index, (number, name) in enumerate(entries):
            raw = struct.pack('<H14s', number, name.encode('ascii'))
            offset = zone*1024 + index*16
            disk[offset:offset+16] = raw

    inode(1, 0o40755, 3, 64, 6)
    inode(2, 0o40755, 2, 32, 7)
    inode(3, 0o100444, 1, len(README), 8)
    directory(6, [(1, '.'), (1, '..'), (2, 'boot'), (3, 'README')])
    directory(7, [(2, '.'), (1, '..')])
    disk[8192:8192+len(README)] = README
    return bytes(disk)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--image', required=True)
    parser.add_argument('--header', required=True)
    args = parser.parse_args()
    disk = build_image()
    Path(args.image).write_bytes(disk)
    # Store only the initialized prefix in firmware. The RAM disk is zeroed
    # by startup; the full .img remains available for independent inspection.
    prefix = disk.rstrip(b'\0')
    lines = ['/* Generated by tools/make_minix_demo.py; do not edit. */',
             'static const unsigned char cp32_demo_bytes[] = {']
    for offset in range(0, len(prefix), 16):
        lines.append('  ' + ','.join(str(x) for x in prefix[offset:offset+16]) + ',')
    lines.append('};\n')
    Path(args.header).write_text('\n'.join(lines))

if __name__ == '__main__':
    main()
